# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Alamofire'
   pod 'AlamofireNetworkActivityLogger'
  pod 'SwiftyJSON'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'NotificationBannerSwift', '2.0.1'
  pod 'SCLAlertView'
  # Pods for POD

end
